services:
  - type: web
    name: tiktok-timer
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: ENABLE_TIKTOK
        value: false
      - key: TIKTOK_USERNAME
        value: siscaa_x
